### ISSUE TITLE
Fail to execute [error]

### ISSUE THREAD

**Issue by unwan878** [erohtar/redditSaver#1]
![image](https://user-images.githubusercontent.com/81401809/206871240-38bbd16b-8634-450c-8690-1ea63f01b441.png)

Hi, I have been trying two version of the script and still showing fail, I have also manually created a file called "saved.json" and the below error occur.
![image](https://user-images.githubusercontent.com/81401809/206871291-19c412b1-dc57-4bc4-9408-d57ee15f60e0.png)

**Comment by erohtar** [comment]
What does your settings.json look like?

**Comment by unwan878** [comment]
Arhh, I see. I have right click and copy the JSON URL which does not include the username in between the jsonUrl. Thank you so much

**Comment by erohtar** [comment]
Glad to know it's resolved. Cheers
