### ISSUE TITLE
Failed, "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by profucius** [erohtar/redditSaver#2]
Hi there, interesting script you've written and I'm trying to get it running. I set everything up according to your instructions, but I'm getting these errors. Note: I downloaded the portable node app you linked in the instructions, and then unzipped your script into the same folder as the node.exe file.

---

First run of the script, I get this error. It seems that the script is not creating its own saved.json file:

```
D:\Apps\Obsidian\redditSaver>node.exe redditSaver.js
fs.js:1112
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink 'D:\Apps\Obsidian\redditSaver\saved.json'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1112:18)
    at Object.<anonymous> (D:\Apps\Obsidian\redditSaver\redditSaver.js:10:4)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
```

---

So I created that saved.json file manually as a blank file via Notepad++, and then I get this error:

```
D:\Apps\Obsidian\redditSaver>node.exe redditSaver.js
saved.json : Downloaded
undefined:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at createNotes (D:\Apps\Obsidian\redditSaver\redditSaver.js:30:19)
    at WriteStream.filePath.on (D:\Apps\Obsidian\redditSaver\redditSaver.js:19:3)
    at emitNone (events.js:91:20)
    at WriteStream.emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:515:14)
    at endWritable (_stream_writable.js:525:3)
    at WriteStream.Writable.end (_stream_writable.js:490:5)
    at IncomingMessage.onend (_stream_readable.js:514:10)
    at IncomingMessage.g (events.js:292:16)
```

---

I triple checked the jsonUrl in the settings.json, and it does show in Firefox as a properly formatted JSON file with trees of posts. So I am not sure what else I've done wrong, or if its something related to a post I have saved (i.e. an improper character, etc).

I have a second reddit account, and I tried the process with that account's private json url, and got the same error as above.

I tried downloading the official latest node app from [their website](https://nodejs.org/en/download/), as a zip package rather than installer, extracted it to a clean folder and unzipped your script into it, followed the same steps, got the same errors.

---

I also tried manually downloading the saved.json file through my browser, dropping it into the script folder, and then I modified your script to comment out the sections in the beginning where it deletes the old json and downloads new one, so that it would skip to processing the current one. I run the script again in a cmd window, and this time it gives no errors, just looks ready for another command, but then I go into the folder I configured for it to download to, and there is nothing there.

If it helps you, here is a copy of my settings.json file, with the token and username omitted:

```
{
	"jsonUrl": "https://www.reddit.com/saved.json?feed=xxx&user=xxx",
	"rootPath": "D:\\Apps\\Obsidian\\MyLife\\Reddit",
	"overWrite": 0
}
```

**Comment by erohtar** [comment]
Hi, You seem to have covered everything in your attempts to get it to work. But since no one else has reported this problem so far, I still have to assume it's something local on your machine that's breaking it.
I do notice that you're missing the `user/erohtar` portion of the jsonUrl in your settings (refer the sample file) - did you try adding it manually and see if it helps anything?

**Comment by profucius** [comment]
> I do notice that you're missing the user/erohtar portion of the jsonUrl

I noticed that too, but the URL I have is straight from Reddit when I right click and copy the JSON button on the feeds page. It offered it to me that exact way in both of my accounts. 

I just tried injecting that text into the URL (modified to my username). and it worked! Hmm, I wonder why the Reddit copied link did not include it. It may be necessary for you to mention that in your instructions.

**Comment by erohtar** [comment]
Alright, if you're sure the url is correct, then try this. You said you already commented out the //delete and //download parts of the code.
Then you can just run `createNotes();` right after that (assuming you already got a correctly formatted, manually downloaded saved.json file in the folder)

Beginning code should look something like this:
![image](https://user-images.githubusercontent.com/5120628/208498785-35d40287-011b-43a2-b435-6f0241ca2695.png)

**Comment by profucius** [comment]
Sorry I believe I edited my previous comment as you were writing your reply. I got it to work by adding that text into the URL as you mentioned. Thank you though.

I don't see any mention of the possibility of this happening within your instructions, so you should add that for future users. Note: I did all of this within Firefox, I'll try it within Chrome to see if it's any different. Update: It did not. I have no idea why I am getting a URL that is not formatted to work in your script across all browsers.

**Comment by erohtar** [comment]
Ah perfect, glad that's resolved. 

Since this has been the only instance of the problem, I'll chalk it down to a temporary reddit glitch. If it happens with more people, I'll update the README

**Comment by profucius** [comment]
Makes sense. I would recommend at least mentioning to pay attention to the URL to ensure that it contains the /user/xxx/ section. It was easy to overlook, I just happened to notice it in glancing. Would've saved me a couple of hours today. 

Anyway, thanks again for making this script! I'm really looking forward to using it.
